{% set name = "gnutls" %}
{% set version_major_minor = "3.6" %}
{% set version = version_major_minor + ".16" %}
{% set sha256 = "1b79b381ac283d8b054368b335c408fedcb9b7144e0c07f531e3537d4328f3b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://www.gnupg.org/ftp/gcrypt/gnutls/v{{ version_major_minor }}/gnutls-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # This patch fixes things for OSX and the old compiler.
    # For some reason it would detect that the compiler has
    # no_weaak_imports, but not actually have it
    - 0001-macosx_no_weak_imports.patch  # [osx and c_compiler=='clang']
    # This patch fixes the pkgconfig test. It looks for the library
    # in the correct place (${PREFIX}/lib and ${PREFIX}/includes) and
    # uses gcc to compile the generated temporary files.
    - 0002-pkgconfig.patch
    # https://gitlab.com/gnutls/gnutls/issues/660
    - 0003-Fix-libcrypto-test-it-must-always-fail.patch
    # https://gitlab.com/gnutls/gnutls/-/issues/967
    - 0004-Fix-status-request-revoked-after-2020-10-24.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=gnutls
    - {{ pin_subpackage('gnutls', max_pin='x.x') }}
  ignore_run_exports:
    # Only used in tests: tests/suite/prime-check.c
    - gmp

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake 1.16.1
    - libtool
    - make
    - pkg-config
  host:
    - gettext >=0.19.8.1     # [osx]
    - gmp
    - nettle >=3.7.2
    # - datefudge              # [linux]
  run:
    # ideally would add run_exports to nettle and gettext and remove these
    - nettle >=3.7.2
    - gettext >=0.19.8.1     # [osx]

test:
  commands:
    - test -f ${PREFIX}/lib/libgnutls${SHLIB_EXT}    # [unix]
    - test -f ${PREFIX}/lib/libgnutlsxx${SHLIB_EXT}  # [unix]

about:
  home: http://www.gnutls.org/index.html
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols'
  doc_url: http://www.gnutls.org/documentation.html
  dev_url: https://gitlab.com/gnutls/gnutls/tree/master

extra:
  recipe-maintainers:
    - sachalau
    - sdvillal
    - scopatz
    - notestaff
