{% set name = "gnutls" %}
{% set version = "3.5.19" %}
{% set sha256 = "1936eb64f03aaefd6eb16cef0567457777618573826b94d03376bb6a4afadc44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: ftp://ftp.gnutls.org/gcrypt/{{ name }}/v3.5/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - pkgconfig.patch
    #this patch fixes the pkgconfig test. It looks for the library
    #in the correct place (${PREFIX}/lib and ${PREFIX}/includes) and
    #uses gcc to compile the generated temporary files.
    - makefile.patch  # [osx]
    #this patches fixes the makefile in tests/slow/. This makefile
    #used to trigger the test on the openssl compatibility module
    #even though it was not built. I added a test on ENABLE_OPENSSL.

build:
  number: 1001
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=gnutls
    - {{ pin_subpackage('gnutls', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - automake
    - libtool
  host:
    - zlib
    - gettext >=0.19.8.1     # [osx]
    - gmp
    - nettle
  run:
    # ideally would add run_exports to nettle and gettext and remove these
    - nettle
    - gettext >=0.19.8.1     # [osx]

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}   # [osx]
    - test -f ${PREFIX}/lib/libgnutls.so       # [linux]
    - test -f ${PREFIX}/lib/libgnutlsxx.so     # [linux]
    - test -f ${PREFIX}/lib/libgnutls.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgnutlsxx.dylib  # [osx]

about:
  home: http://www.gnutls.org/index.html
  license: GPL 2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols'
  doc_url: http://www.gnutls.org/documentation.html
  dev_url: https://gitlab.com/gnutls/gnutls/tree/master

extra:
  recipe-maintainers:
    - sachalau
    - sdvillal
