appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TRcqL0yjOQ+JcKoGvdjdRIq52aK9PWAx0QG/hCaHp3GADBs4w7UPfwiBhm2mYmssiQbpoflHJlzU01MaKxiiw9ZxFq3Mr9tGRNb7a1qpXWW6PSZXPbHIgEXTKqNWyaldtR+JnojDY68noQmVExOCZtsp8YkURgJ4lJAMvzllUK1he9lK+p1PXbuqpZ5Yh3FvkmllGWqBTqKTWILxSYcF0aL6cqd+/1CTQPLUL6alL+sQ8E5N95u0kIMF4kcMxmOzd2/9I0hDGIzoddK+de6jzZD4qppxFghZ9ccDCCEtZH1S2Sctj2zkmG+qzLeFA2sY9U4VY3k6Vc1c4dqdcHa90s8SEmYgReh5DPbXnqjTPZautna5HWHpqH2nusfxYUCSCIVb5Sft3h037dBArwJDeok8QfNFeboohdePI84jbyfOLw9BMpRRlXGEArsNANQ4d7WP/mfcx8t82OGtIaqcoQlSCMMxq+Out0vepzF+X0orDQ5MIe3sEu9kEu/XS23/gyBY1wyoxNuodfemZlrgTZHw8dl2mKrd48A1JBBbNHBMzlq92YOb1L4jKfE+vkxjWop0KaAi40kXjFkbbbpwb57U1vzSHGfOgEk1IBq8yM1Wf0BYeyb43Fjlqdr1Kkh0O7rKUjYT0Tr2yaee5hi+DY6PE301v72UCpgbj39r3sI=}
